<form method="post" enctype="multipart/form-data">
	<h2>
		Admin &gt;
		<a href="<?=$this->url('admin', array('action' => 'list', 'model' => $model))?>"><?=\ATP\Inflector::pluralize($modelData['displayName'])?></a> &gt;
		Module Parameters
		<input type="submit" class="model-save" name="submit" value="Save Parameters" />
	</h2>

	<div id="admin-tabs">
		<ul>
			<?php foreach(array_keys($params) as $group) { ?>
				<li><a href="#<?=$group?>-tab"><?=$group?></a></li>
			<?php } ?>
		</ul>
			<?php foreach($params as $group => $paramList) { ?>
				<div id="<?=$group?>-tab">
					<div class="admin-edit model-edit-form">
						<?php foreach($paramList as $id => $param) { ?>
							<?php $helper = "form{$param['type']}"?>
							<?php $value = isset($objects[$param['identifier']]) ? $objects[$param['identifier']]->value : $param['default']?>
							<?=$this->$helper(array_merge(
								array('label' => $param['identifier'], 'name' => "params[{$group}][{$id}]", 'value' => $value),
								isset($param['options']) ? $param['options'] : array()
							))?>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
	</div>
</form>
